### ISSUE TITLE
Edge glow effect have margin in the dialog

### ISSUE THREAD

**Issue by FranckRJ** [Gericop/ColorPicker#1]
Up : Google SMS app
Down : an app with this library

![](https://i.imgur.com/fOuoYO9.png)

Is it possible to have the same behavior as the google app ?

**Comment by gregkorossy** [comment]
Sorry, didn't notice this issue. I'll check it out.

**Comment by gregkorossy** [comment]
It's gonna be fixed in **1.0.2**. Note, however, that the scrollbars will not be visible because they seem to be buggy for whatever reason (they do not move or move in a completely messed up way).

**Comment by FranckRJ** [comment]
Thanks, a proper edge glow effect is enough.

**Comment by gregkorossy** [comment]
It's available in v**1.0.2**.
